/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

# Authenticator route
/login:
  controller: authenticator
  action: login

/logout:
  controller: authenticator
  action: logout

/register:
  controller: authenticator
  action: register

/forget:
  controller: authenticator
  action: pwdforget

# User controller route
/users:
  controller: user
  action: index

/user/show:
  controller: user
  action: show

/user/edit:
  controller: user
  action: edit

/user/update:
  controller: user
  action: update

/user/delete:
  controller: user
  action: delete

# Page controller route
/pages:
  controller: page
  action: index

/page/add:
  controller: page
  action: add

/page/showPage:
  controller: page
  action: showPage

/page/edit:
  controller: page
  action: edit

/page/update:
  controller: page
  action: update

/page/delete:
  controller: page
  action: delete


# Article controller route
/articles:
  controller: article
  action: index

/article/add:
  controller: article
  action: add

/article/showArticle:
  controller: article
  action: showArticle

/article/edit:
  controller: article
  action: edit

/article/update:
  controller: article
  action: update

/article/delete:
  controller: article
  action: delete