/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

# user controller routes

/login:
  controller: user
  action: login
  parametres:

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user
