/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

# User controller route # 
/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/user/index:
  controller: user
  action: index

/user/show:
  controller: user
  action: show

/user/edit:
  controller: user
  action: edit

/user/update:
  controller: user
  action: update

/user/delete:
  controller: user
  action: delete

